[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd ../frontend && npm install",
  "cd ../docs-site && npm install"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd ../frontend && npm run build",
  "cd ../docs-site && npm run build"
]

[start]
cmd = "cd backend && npm run start"

